version: "2"
services:
  api:
    environment:
      - TRACKING_REST_DB="dbname=tracing_rest_dev user=postgres sslmode=disable"
      - TRACKING_REST_PORT="3000"
    build: .
    container_name: tracing_rest
    command: tracing-rest
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/github.com/rafaeljesus/tracing-rest
    links:
      - db
  db:
    container_name: postgres_dev
    image: postgres:9.4.2
    ports:
      - "5432:5432"
    volumes:
      - /Users/rafaeljesus/mnt/sda1/data/postgresql:/var/lib/postgresql/data
